class Autogenerated {
  bool? success;
  String? message;
  ProfileModel? data;

  Autogenerated({this.success, this.message, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    success = json['success'] ?? false;
    message = json['message'] ?? '';
    data = json['data'] != null ? ProfileModel.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class ProfileModel {
  User? user;
  DeliveryBoy? deliveryBoy;

  ProfileModel({this.user, this.deliveryBoy});

  ProfileModel.fromJson(Map<String, dynamic> json) {
    user = json['user'] != null ? User.fromJson(json['user']) : null;
    deliveryBoy =
        json['delivery_boy'] != null
            ? DeliveryBoy.fromJson(json['delivery_boy'])
            : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    if (user != null) {
      data['user'] = user!.toJson();
    }
    if (deliveryBoy != null) {
      data['delivery_boy'] = deliveryBoy!.toJson();
    }
    return data;
  }
}

class User {
  int? id;
  String? name;
  String? email;
  String? mobile;
  String? country;
  String? iso2;
  double? walletBalance;
  String? referralCode;
  String? friendsCode;
  int? rewardPoints;
  String? profileImage;
  String? emailVerifiedAt;
  String? createdAt;
  String? updatedAt;
  String? status;

  User({
    this.id,
    this.name,
    this.email,
    this.mobile,
    this.country,
    this.iso2,
    this.walletBalance,
    this.referralCode,
    this.friendsCode,
    this.rewardPoints,
    this.profileImage,
    this.emailVerifiedAt,
    this.createdAt,
    this.updatedAt,
    this.status, // Added missing field
  });

  User.fromJson(Map<String, dynamic> json) {
    id = _parseInt(json['id']);
    name = json['name'];
    email = json['email'];
    mobile = json['mobile'];
    country = json['country'];
    iso2 = json['iso_2'];
    walletBalance = _parseDouble(json['wallet_balance']);
    referralCode = json['referral_code'];
    friendsCode = json['friends_code'];
    rewardPoints = _parseInt(json['reward_points']);
    profileImage = json['profile_image'];
    emailVerifiedAt = json['email_verified_at'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    status = json['status'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['email'] = email;
    data['mobile'] = mobile;
    data['country'] = country;
    data['iso_2'] = iso2;
    data['wallet_balance'] = walletBalance;
    data['referral_code'] = referralCode;
    data['friends_code'] = friendsCode;
    data['reward_points'] = rewardPoints;
    data['profile_image'] = profileImage;
    data['email_verified_at'] = emailVerifiedAt;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['status'] = status; // Added missing field
    return data;
  }
}

class DeliveryBoy {
  int? id;
  int? userId;
  int? deliveryZoneId;
  String? status;
  String? fullName;
  String? address;
  List<String>? driverLicense;
  String? driverLicenseNumber;
  String? vehicleType;
  List<String>? vehicleRegistration;
  String? verificationStatus;
  String? verificationRemark;
  String? createdAt;
  String? updatedAt; // Added missing field
  String? deletedAt; // Added missing field
  DeliveryZone? deliveryZone; // Added missing field
  List<Media>? media; // Added missing field

  DeliveryBoy({
    this.id,
    this.userId,
    this.deliveryZoneId,
    this.status,
    this.fullName,
    this.address,
    this.driverLicense,
    this.driverLicenseNumber,
    this.vehicleType,
    this.vehicleRegistration,
    this.verificationStatus,
    this.verificationRemark,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
    this.deliveryZone,
    this.media,
  });

  DeliveryBoy.fromJson(Map<String, dynamic> json) {
    id = _parseInt(json['id']);
    userId = _parseInt(json['user_id']);
    deliveryZoneId = _parseInt(json['delivery_zone_id']);
    status = json['status'];
    fullName = json['full_name'];
    address = json['address'];
    driverLicense =
        json['driver_license'] != null
            ? List<String>.from(json['driver_license'])
            : null;
    driverLicenseNumber = json['driver_license_number'];
    vehicleType = json['vehicle_type'];
    vehicleRegistration =
        json['vehicle_registration'] != null
            ? List<String>.from(json['vehicle_registration'])
            : null;
    verificationStatus = json['verification_status'];
    verificationRemark = json['verification_remark'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    deletedAt = json['deleted_at'];
    deliveryZone =
        json['delivery_zone'] != null
            ? DeliveryZone.fromJson(json['delivery_zone'])
            : null;
    media = <Media>[];
    if (json['media'] != null) {
      json['media'].forEach((v) {
        media!.add(Media.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['user_id'] = userId;
    data['delivery_zone_id'] = deliveryZoneId;
    data['status'] = status;
    data['full_name'] = fullName;
    data['address'] = address;
    data['driver_license'] = driverLicense;
    data['driver_license_number'] = driverLicenseNumber;
    data['vehicle_type'] = vehicleType;
    data['vehicle_registration'] = vehicleRegistration;
    data['verification_status'] = verificationStatus;
    data['verification_remark'] = verificationRemark;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt; // Added missing field
    data['deleted_at'] = deletedAt; // Added missing field
    if (deliveryZone != null) {
      data['delivery_zone'] = deliveryZone!.toJson();
    } // Added missing field
    if (media != null) {
      data['media'] = media!.map((v) => v.toJson()).toList();
    } // Added missing field
    return data;
  }
}

class DeliveryZone {
  int? id;
  String? name;
  String? slug;
  String? centerLatitude;
  String? centerLongitude;
  double? radiusKm;
  int? rushDeliveryTimePerKm;
  int? rushDeliveryCharges;
  int? deliveryTimePerKm;
  int? regularDeliveryCharges;
  double? freeDeliveryAmount;
  double? distanceBasedDeliveryCharges;
  double? perStoreDropOffFee;
  double? handlingCharges;
  String? deliveryBoyBaseFee;
  String? deliveryBoyPerStorePickupFee;
  String? deliveryBoyDistanceBasedFee;
  String? deliveryBoyPerOrderIncentive;
  int? bufferTime;
  List<BoundaryJson>? boundaryJson;
  bool? rushDeliveryEnabled;
  String? status;
  String? createdAt;
  String? updatedAt;

  DeliveryZone({
    this.id,
    this.name,
    this.slug,
    this.centerLatitude,
    this.centerLongitude,
    this.radiusKm,
    this.rushDeliveryTimePerKm,
    this.rushDeliveryCharges,
    this.deliveryTimePerKm,
    this.regularDeliveryCharges,
    this.freeDeliveryAmount,
    this.distanceBasedDeliveryCharges,
    this.perStoreDropOffFee,
    this.handlingCharges,
    this.deliveryBoyBaseFee,
    this.deliveryBoyPerStorePickupFee,
    this.deliveryBoyDistanceBasedFee,
    this.deliveryBoyPerOrderIncentive,
    this.bufferTime,
    this.boundaryJson,
    this.rushDeliveryEnabled,
    this.status,
    this.createdAt,
    this.updatedAt,
  });

  DeliveryZone.fromJson(Map<String, dynamic> json) {
    id = _parseInt(json['id']);
    name = json['name'];
    slug = json['slug'];
    centerLatitude = json['center_latitude'];
    centerLongitude = json['center_longitude'];
    radiusKm = _parseDouble(json['radius_km']);
    rushDeliveryTimePerKm = _parseInt(json['rush_delivery_time_per_km']);
    rushDeliveryCharges = _parseInt(json['rush_delivery_charges']);
    deliveryTimePerKm = _parseInt(json['delivery_time_per_km']);
    regularDeliveryCharges = _parseInt(json['regular_delivery_charges']);
    freeDeliveryAmount = _parseDouble(json['free_delivery_amount']);
    distanceBasedDeliveryCharges = _parseDouble(
      json['distance_based_delivery_charges'],
    );
    perStoreDropOffFee = _parseDouble(json['per_store_drop_off_fee']);
    handlingCharges = _parseDouble(json['handling_charges']);
    deliveryBoyBaseFee = json['delivery_boy_base_fee']?.toString();
    deliveryBoyPerStorePickupFee =
        json['delivery_boy_per_store_pickup_fee']?.toString();
    deliveryBoyDistanceBasedFee =
        json['delivery_boy_distance_based_fee']?.toString();
    deliveryBoyPerOrderIncentive =
        json['delivery_boy_per_order_incentive']?.toString();
    bufferTime = _parseInt(json['buffer_time']);
    boundaryJson = <BoundaryJson>[];
    if (json['boundary_json'] != null) {
      json['boundary_json'].forEach((v) {
        boundaryJson!.add(BoundaryJson.fromJson(v));
      });
    }
    rushDeliveryEnabled =
        json['rush_delivery_enabled'] == true ||
        json['rush_delivery_enabled'] == 'true';
    status = json['status'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['slug'] = slug;
    data['center_latitude'] = centerLatitude;
    data['center_longitude'] = centerLongitude;
    data['radius_km'] = radiusKm;
    data['rush_delivery_time_per_km'] = rushDeliveryTimePerKm;
    data['rush_delivery_charges'] = rushDeliveryCharges;
    data['delivery_time_per_km'] = deliveryTimePerKm;
    data['regular_delivery_charges'] = regularDeliveryCharges;
    data['free_delivery_amount'] = freeDeliveryAmount;
    data['distance_based_delivery_charges'] = distanceBasedDeliveryCharges;
    data['per_store_drop_off_fee'] = perStoreDropOffFee;
    data['handling_charges'] = handlingCharges;
    data['delivery_boy_base_fee'] = deliveryBoyBaseFee;
    data['delivery_boy_per_store_pickup_fee'] = deliveryBoyPerStorePickupFee;
    data['delivery_boy_distance_based_fee'] = deliveryBoyDistanceBasedFee;
    data['delivery_boy_per_order_incentive'] = deliveryBoyPerOrderIncentive;
    data['buffer_time'] = bufferTime;
    if (boundaryJson != null) {
      data['boundary_json'] = boundaryJson!.map((v) => v.toJson()).toList();
    }
    data['rush_delivery_enabled'] = rushDeliveryEnabled;
    data['status'] = status;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    return data;
  }
}

class BoundaryJson {
  double? lat;
  double? lng;

  BoundaryJson({this.lat, this.lng});

  BoundaryJson.fromJson(Map<String, dynamic> json) {
    lat = _parseDouble(json['lat']);
    lng = _parseDouble(json['lng']);
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['lat'] = lat;
    data['lng'] = lng;
    return data;
  }
}

class Media {
  int? id;
  String? modelType;
  int? modelId;
  String? uuid;
  String? collectionName;
  String? name;
  String? fileName;
  String? mimeType;
  String? disk;
  String? conversionsDisk;
  int? size;
  List<dynamic>? manipulations;
  List<dynamic>? customProperties;
  List<dynamic>? generatedConversions;
  List<dynamic>? responsiveImages;
  int? orderColumn;
  String? createdAt;
  String? updatedAt;
  String? originalUrl;
  String? previewUrl;

  Media({
    this.id,
    this.modelType,
    this.modelId,
    this.uuid,
    this.collectionName,
    this.name,
    this.fileName,
    this.mimeType,
    this.disk,
    this.conversionsDisk,
    this.size,
    this.manipulations,
    this.customProperties,
    this.generatedConversions,
    this.responsiveImages,
    this.orderColumn,
    this.createdAt,
    this.updatedAt,
    this.originalUrl,
    this.previewUrl,
  });

  Media.fromJson(Map<String, dynamic> json) {
    id = _parseInt(json['id']);
    modelType = json['model_type'];
    modelId = _parseInt(json['model_id']);
    uuid = json['uuid'];
    collectionName = json['collection_name'];
    name = json['name'];
    fileName = json['file_name'];
    mimeType = json['mime_type'];
    disk = json['disk'];
    conversionsDisk = json['conversions_disk'];
    size = _parseInt(json['size']);
    manipulations = json['manipulations']?.cast<dynamic>();
    customProperties = json['custom_properties']?.cast<dynamic>();
    generatedConversions = json['generated_conversions']?.cast<dynamic>();
    responsiveImages = json['responsive_images']?.cast<dynamic>();
    orderColumn = _parseInt(json['order_column']);
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    originalUrl = json['original_url'];
    previewUrl = json['preview_url'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['model_type'] = modelType;
    data['model_id'] = modelId;
    data['uuid'] = uuid;
    data['collection_name'] = collectionName;
    data['name'] = name;
    data['file_name'] = fileName;
    data['mime_type'] = mimeType;
    data['disk'] = disk;
    data['conversions_disk'] = conversionsDisk;
    data['size'] = size;
    data['manipulations'] = manipulations;
    data['custom_properties'] = customProperties;
    data['generated_conversions'] = generatedConversions;
    data['responsive_images'] = responsiveImages;
    data['order_column'] = orderColumn;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['original_url'] = originalUrl;
    data['preview_url'] = previewUrl;
    return data;
  }
}

// Global helper methods for safe parsing
double? _parseDouble(dynamic value) {
  if (value == null) return null;
  if (value is double) return value;
  if (value is int) return value.toDouble();
  if (value is String) {
    try {
      return double.parse(value);
    } catch (e) {
      return null;
    }
  }
  return null;
}

int? _parseInt(dynamic value) {
  if (value == null) return null;
  if (value is int) return value;
  if (value is double) return value.toInt();
  if (value is String) {
    try {
      return int.parse(value);
    } catch (e) {
      return null;
    }
  }
  return null;
}
