// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_n, avoid_classes_with_only_static_methods
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // You'll need to replace these with your actual Firebase project configuration
  // Get these values from your Firebase Console: Project Settings > General > Your apps

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8HxdhMeS5w1ZDHC1D1jiTmuLzbBVOAK8',
    appId: '1:731593120675:web:d082702f404ce520a49816',
    messagingSenderId: '731593120675',
    projectId: 'grofery-rider-prod-ax',
    authDomain: 'grofery-rider-prod-ax.firebaseapp.com',
    storageBucket: 'grofery-rider-prod-ax.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIxCXBCksBKvWY_4YkLb_if_VCeqlyrAI',
    appId: '1:731593120675:android:713565c18af1ead3a49816',
    messagingSenderId: '731593120675',
    projectId: 'grofery-rider-prod-ax',
    storageBucket: 'grofery-rider-prod-ax.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4G4p4bznY4tflhonYSfoI-OEeWluqJ-U',
    appId: '1:731593120675:ios:8f9a56409b339f00a49816',
    messagingSenderId: '731593120675',
    projectId: 'grofery-rider-prod-ax',
    storageBucket: 'grofery-rider-prod-ax.firebasestorage.app',
    iosBundleId: 'com.axolotls.grofery.rider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4G4p4bznY4tflhonYSfoI-OEeWluqJ-U',
    appId: '1:731593120675:ios:347430859a1a56b7a49816',
    messagingSenderId: '731593120675',
    projectId: 'grofery-rider-prod-ax',
    storageBucket: 'grofery-rider-prod-ax.firebasestorage.app',
    iosBundleId: 'com.example.hyperLocal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8HxdhMeS5w1ZDHC1D1jiTmuLzbBVOAK8',
    appId: '1:731593120675:web:46fe0b6cbd1245c2a49816',
    messagingSenderId: '731593120675',
    projectId: 'grofery-rider-prod-ax',
    authDomain: 'grofery-rider-prod-ax.firebaseapp.com',
    storageBucket: 'grofery-rider-prod-ax.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions  (
    apiKey: 'your-linux-api-key',
    appId: 'your-linux-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
  );
}