class Autogenerated {
  bool? success;
  String? message;
  SettingsModel? data;

  Autogenerated({this.success, this.message, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message'];
    data = json['data'] != null ? SettingsModel.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class SettingsModel {
  List<SettingItem>? data;

  SettingsModel({this.data});

  SettingsModel.fromJson(Map<String, dynamic> json) {
    // Debug logging


    
    // The API response structure can vary:
    // 1. Sometimes 'data' is a List of SettingItem objects
    // 2. Sometimes 'data' is a Map containing currency info directly
    if (json['data'] != null) {
      if (json['data'] is List) {
        // Case 1: data is a List of SettingItem objects
        data = <SettingItem>[];
        json['data'].forEach((v) {
          data!.add(SettingItem.fromJson(v));
        });

      } else if (json['data'] is Map) {
        // Case 2: data is a Map containing currency info directly
        // Create a single SettingItem with 'system' variable
        data = <SettingItem>[];
        final systemData = json['data'] as Map<String, dynamic>;
        
        // Check if this Map contains currency information
        if (systemData.containsKey('currency') || systemData.containsKey('currencySymbol') || systemData.containsKey('currency_symbol')) {
          // Create a system SettingItem
          final systemItem = SettingItem(
            variable: 'system',
            value: Value.fromJson(systemData),
          );
          data!.add(systemItem);
        } else {
          // If no currency info, try to parse as regular SettingItem
          // Also check if this map *is* the settings (like terms/privacy)
          final settingItem = SettingItem.fromJson(systemData);
          if (settingItem.variable != null) {
            data!.add(settingItem);
          } else if (systemData.containsKey('termsCondition') || 
                     systemData.containsKey('terms_condition') ||
                     systemData.containsKey('privacyPolicy') ||
                     systemData.containsKey('privacy_policy')) {
            // It looks like this map is the delivery boy settings itself
            final deliveryItem = SettingItem(
              variable: 'delivery_boy',
              value: Value.fromJson(systemData),
            );
            data!.add(deliveryItem);
          }
        }
      }
    }
    

  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }

  // Helper method to get delivery boy system_settings (contains terms and privacy policy)
  SettingItem? get deliveryBoySettings {
    // First, try to find a setting item with variable == 'delivery_boy'
    SettingItem? deliveryBoyItem = data?.cast<SettingItem?>().firstWhere(
      (item) => item?.variable == 'delivery_boy',
      orElse: () => null,
    );
    
    // If found, return it
    if (deliveryBoyItem != null) {
      return deliveryBoyItem;
    }
    
    // If not found, look for system system_settings which contain currency information
    return data?.cast<SettingItem?>().firstWhere(
      (item) => item?.variable == 'system',
      orElse: () => null,
    );
  }

  // Helper method to get system system_settings (contains currency information)
  SettingItem? get systemSettings {
    return data?.cast<SettingItem?>().firstWhere(
      (item) => item?.variable == 'system',
      orElse: () => null,
    );
  }

  // Helper method to get currency symbol from system system_settings
  String? get currencySymbol {
    final symbol = systemSettings?.value?.currencySymbol;



    return symbol;
  }

  // Helper method to get currency code from system system_settings
  String? get currency => systemSettings?.value?.currency;

  // Helper method to get terms and conditions
  String? get termsCondition => deliveryBoySettings?.value?.termsCondition;

  // Helper method to get privacy policy
  String? get privacyPolicy => deliveryBoySettings?.value?.privacyPolicy;
}

class SettingItem {
  String? variable;
  Value? value;

  SettingItem({this.variable, this.value});

  SettingItem.fromJson(Map<String, dynamic> json) {
    variable = json['variable'];
    value = json['value'] != null ? Value.fromJson(json['value']) : null;
    // Debug logging

  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['variable'] = variable;
    if (value != null) {
      data['value'] = value!.toJson();
    }
    return data;
  }
}

class Value {
  String? appName;
  String? sellerSupportNumber;
  String? sellerSupportEmail;
  String? systemTimezone;
  String? copyrightDetails;
  String? logo;
  String? favicon;
  bool? enableThirdPartyStoreSync;
  bool? shopify;
  bool? woocommerce;
  bool? etsy;
  int? minimumCartAmount;
  int? maximumItemsAllowedInCart;
  String? lowStockLimit;
  String? maximumDistanceToNearestStore;
  bool? enableWallet;
  int? welcomeWalletBalanceAmount;
  bool? sellerAppMaintenanceMode;
  String? sellerAppMaintenanceMessage;
  bool? webMaintenanceMode;
  String? webMaintenanceMessage;
  bool? demoMode;
  String? adminDemoModeMessage;
  String? sellerDemoModeMessage;
  String? customerDemoModeMessage;
  String? customerLocationDemoModeMessage;
  String? deliveryBoyDemoModeMessage;
  bool? referEarnStatus;
  String? referEarnMethodUser;
  String? referEarnBonusUser;
  String? referEarnMaximumBonusAmountUser;
  String? referEarnMethodReferral;
  String? referEarnBonusReferral;
  String? referEarnMaximumBonusAmountReferral;
  String? referEarnMinimumOrderAmount;
  String? referEarnNumberOfTimesBonus;
  String? currency;
  String? currencySymbol;
  
  // Web system_settings fields (contains terms and privacy policy)
  String? returnRefundPolicy;
  String? privacyPolicy;
  String? termsCondition;

  Value(
      {this.appName,
        this.sellerSupportNumber,
        this.sellerSupportEmail,
        this.systemTimezone,
        this.copyrightDetails,
        this.logo,
        this.favicon,
        this.enableThirdPartyStoreSync,
        this.shopify,
        this.woocommerce,
        this.etsy,
        this.minimumCartAmount,
        this.maximumItemsAllowedInCart,
        this.lowStockLimit,
        this.maximumDistanceToNearestStore,
        this.enableWallet,
        this.welcomeWalletBalanceAmount,
        this.sellerAppMaintenanceMode,
        this.sellerAppMaintenanceMessage,
        this.webMaintenanceMode,
        this.webMaintenanceMessage,
        this.demoMode,
        this.adminDemoModeMessage,
        this.sellerDemoModeMessage,
        this.customerDemoModeMessage,
        this.customerLocationDemoModeMessage,
        this.deliveryBoyDemoModeMessage,
        this.referEarnStatus,
        this.referEarnMethodUser,
        this.referEarnBonusUser,
        this.referEarnMaximumBonusAmountUser,
        this.referEarnMethodReferral,
        this.referEarnBonusReferral,
        this.referEarnMaximumBonusAmountReferral,
        this.referEarnMinimumOrderAmount,
        this.referEarnNumberOfTimesBonus,
        this.currency,
        this.currencySymbol,
        this.returnRefundPolicy,
        this.privacyPolicy,
        this.termsCondition});

  Value.fromJson(Map<String, dynamic> json) {
    appName = json['appName'];
    sellerSupportNumber = json['sellerSupportNumber'];
    sellerSupportEmail = json['sellerSupportEmail'];
    systemTimezone = json['systemTimezone'];
    copyrightDetails = json['copyrightDetails'];
    logo = json['logo'];
    favicon = json['favicon'];
    enableThirdPartyStoreSync = json['enableThirdPartyStoreSync'];
    shopify = json['Shopify'];
    woocommerce = json['Woocommerce'];
    etsy = json['etsy'];
    minimumCartAmount = json['minimumCartAmount'];
    maximumItemsAllowedInCart = json['maximumItemsAllowedInCart'];
    lowStockLimit = json['lowStockLimit'];
    maximumDistanceToNearestStore = json['maximumDistanceToNearestStore'];
    enableWallet = json['enableWallet'];
    welcomeWalletBalanceAmount = json['welcomeWalletBalanceAmount'];
    sellerAppMaintenanceMode = json['sellerAppMaintenanceMode'];
    sellerAppMaintenanceMessage = json['sellerAppMaintenanceMessage'];
    webMaintenanceMode = json['webMaintenanceMode'];
    webMaintenanceMessage = json['webMaintenanceMessage'];
    demoMode = json['demoMode'];
    adminDemoModeMessage = json['adminDemoModeMessage'];
    sellerDemoModeMessage = json['sellerDemoModeMessage'];
    customerDemoModeMessage = json['customerDemoModeMessage'];
    customerLocationDemoModeMessage = json['customerLocationDemoModeMessage'];
    deliveryBoyDemoModeMessage = json['deliveryBoyDemoModeMessage'];
    referEarnStatus = json['referEarnStatus'];
    referEarnMethodUser = json['referEarnMethodUser'];
    referEarnBonusUser = json['referEarnBonusUser'];
    referEarnMaximumBonusAmountUser = json['referEarnMaximumBonusAmountUser'];
    referEarnMethodReferral = json['referEarnMethodReferral'];
    referEarnBonusReferral = json['referEarnBonusReferral'];
    referEarnMaximumBonusAmountReferral =
    json['referEarnMaximumBonusAmountReferral'];
    referEarnMinimumOrderAmount = json['referEarnMinimumOrderAmount'];
    referEarnNumberOfTimesBonus = json['referEarnNumberOfTimesBonus'];
    currency = json['currency'];
    currencySymbol = json['currencySymbol'] ?? json['currency_symbol'];
    
    // Debug logging for currency
    if (json['currency'] != null || json['currencySymbol'] != null || json['currency_symbol'] != null) {



    }
    returnRefundPolicy = json['returnRefundPolicy'] ?? json['return_refund_policy'];
    privacyPolicy = json['privacyPolicy'] ?? json['privacy_policy'];
    termsCondition = json['termsCondition'] ?? json['terms_condition'];
    
    // Debug logging for web system_settings
    if (json['returnRefundPolicy'] != null || json['privacyPolicy'] != null) {



    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['appName'] = appName;
    data['sellerSupportNumber'] = sellerSupportNumber;
    data['sellerSupportEmail'] = sellerSupportEmail;
    data['systemTimezone'] = systemTimezone;
    data['copyrightDetails'] = copyrightDetails;
    data['logo'] = logo;
    data['favicon'] = favicon;
    data['enableThirdPartyStoreSync'] = enableThirdPartyStoreSync;
    data['Shopify'] = shopify;
    data['Woocommerce'] = woocommerce;
    data['etsy'] = etsy;
    data['minimumCartAmount'] = minimumCartAmount;
    data['maximumItemsAllowedInCart'] = maximumItemsAllowedInCart;
    data['lowStockLimit'] = lowStockLimit;
    data['maximumDistanceToNearestStore'] = maximumDistanceToNearestStore;
    data['enableWallet'] = enableWallet;
    data['welcomeWalletBalanceAmount'] = welcomeWalletBalanceAmount;
    data['sellerAppMaintenanceMode'] = sellerAppMaintenanceMode;
    data['sellerAppMaintenanceMessage'] = sellerAppMaintenanceMessage;
    data['webMaintenanceMode'] = webMaintenanceMode;
    data['webMaintenanceMessage'] = webMaintenanceMessage;

    data['demoMode'] = demoMode;
    data['adminDemoModeMessage'] = adminDemoModeMessage;
    data['sellerDemoModeMessage'] = webMaintenanceMessage;
    data['customerDemoModeMessage'] = customerDemoModeMessage;
    data['customerLocationDemoModeMessage'] = customerLocationDemoModeMessage;
    data['deliveryBoyDemoModeMessage'] = deliveryBoyDemoModeMessage;

    data['referEarnStatus'] = referEarnStatus;
    data['referEarnMethodUser'] = referEarnMethodUser;
    data['referEarnBonusUser'] = referEarnBonusUser;
    data['referEarnMaximumBonusAmountUser'] =
        referEarnMaximumBonusAmountUser;
    data['referEarnMethodReferral'] = referEarnMethodReferral;
    data['referEarnBonusReferral'] = referEarnBonusReferral;
    data['referEarnMaximumBonusAmountReferral'] =
        referEarnMaximumBonusAmountReferral;
    data['referEarnMinimumOrderAmount'] = referEarnMinimumOrderAmount;
    data['referEarnNumberOfTimesBonus'] = referEarnNumberOfTimesBonus;
    data['currency'] = currency;
    data['currencySymbol'] = currencySymbol;
    data['returnRefundPolicy'] = returnRefundPolicy;
    data['privacyPolicy'] = privacyPolicy;
    data['termsCondition'] = termsCondition;
    return data;
  }
}
