import 'dart:io';

class Autogenerated {
  bool? success;
  String? message;
  DeliveryBoyStatusModel? data;

  Autogenerated({this.success, this.message, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message'];
    data = json['data'] != null ? DeliveryBoyStatusModel.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class DeliveryBoyStatusModel {
  DeliveryBoy? deliveryBoy;

  DeliveryBoyStatusModel({this.deliveryBoy});

  DeliveryBoyStatusModel.fromJson(Map<String, dynamic> json) {
    deliveryBoy = json['delivery_boy'] != null
        ? DeliveryBoy.fromJson(json['delivery_boy'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    if (deliveryBoy != null) {
      data['delivery_boy'] = deliveryBoy!.toJson();
    }
    return data;
  }
}

class DeliveryBoy {
  int? id;
  int? userId;
  int? deliveryZoneId;
  String? fullName;
  String? address;
  File? driverLicense;
  String? driverLicenseNumber;
  String? vehicleType;
  File? vehicleRegistration;
  String? verificationStatus;
  String? verificationRemark;
  String? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;
  DeliveryZone? deliveryZone;

  DeliveryBoy(
      {this.id,
        this.userId,
        this.deliveryZoneId,
        this.fullName,
        this.address,
        this.driverLicense,
        this.driverLicenseNumber,
        this.vehicleType,
        this.vehicleRegistration,
        this.verificationStatus,
        this.verificationRemark,
        this.status,
        this.createdAt,
        this.updatedAt,
        this.deletedAt,
        this.deliveryZone});

  DeliveryBoy.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    userId = json['user_id'];
    deliveryZoneId = json['delivery_zone_id'];
    fullName = json['full_name'];
    address = json['address'];
    driverLicense = json['driver_license'];
    driverLicenseNumber = json['driver_license_number'];
    vehicleType = json['vehicle_type'];
    vehicleRegistration = json['vehicle_registration'];
    verificationStatus = json['verification_status'];
    verificationRemark = json['verification_remark'];
    status = json['status'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    deletedAt = json['deleted_at'];
    deliveryZone = json['delivery_zone'] != null
        ? DeliveryZone.fromJson(json['delivery_zone'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['user_id'] = userId;
    data['delivery_zone_id'] = deliveryZoneId;
    data['full_name'] = fullName;
    data['address'] = address;
    data['driver_license'] = driverLicense;
    data['driver_license_number'] = driverLicenseNumber;
    data['vehicle_type'] = vehicleType;
    data['vehicle_registration'] = vehicleRegistration;
    data['verification_status'] = verificationStatus;
    data['verification_remark'] = verificationRemark;
    data['status'] = status;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['deleted_at'] = deletedAt;
    if (deliveryZone != null) {
      data['delivery_zone'] = deliveryZone!.toJson();
    }
    return data;
  }
}

class DeliveryZone {
  int? id;
  String? name;
  String? slug;
  String? centerLatitude;
  String? centerLongitude;
  double? radiusKm;
  double? rushDeliveryTimePerKm;
  double? rushDeliveryCharges;
  int? deliveryTimePerKm;
  int? regularDeliveryCharges;
  double? freeDeliveryAmount;
  double? distanceBasedDeliveryCharges;
  double? perStoreDropOffFee;
  double? handlingCharges;
  double? deliveryBoyBaseFee;
  double? deliveryBoyPerStorePickupFee;
  double? deliveryBoyDistanceBasedFee;
  double? deliveryBoyPerOrderIncentive;
  int? bufferTime;
  List<BoundaryJson>? boundaryJson;
  bool? rushDeliveryEnabled;
  String? status;
  String? createdAt;
  String? updatedAt;

  DeliveryZone(
      {this.id,
        this.name,
        this.slug,
        this.centerLatitude,
        this.centerLongitude,
        this.radiusKm,
        this.rushDeliveryTimePerKm,
        this.rushDeliveryCharges,
        this.deliveryTimePerKm,
        this.regularDeliveryCharges,
        this.freeDeliveryAmount,
        this.distanceBasedDeliveryCharges,
        this.perStoreDropOffFee,
        this.handlingCharges,
        this.deliveryBoyBaseFee,
        this.deliveryBoyPerStorePickupFee,
        this.deliveryBoyDistanceBasedFee,
        this.deliveryBoyPerOrderIncentive,
        this.bufferTime,
        this.boundaryJson,
        this.rushDeliveryEnabled,
        this.status,
        this.createdAt,
        this.updatedAt});

  DeliveryZone.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    slug = json['slug'];
    centerLatitude = json['center_latitude'];
    centerLongitude = json['center_longitude'];
    radiusKm = json['radius_km'];
    rushDeliveryTimePerKm = json['rush_delivery_time_per_km'];
    rushDeliveryCharges = json['rush_delivery_charges'];
    deliveryTimePerKm = json['delivery_time_per_km'];
    regularDeliveryCharges = json['regular_delivery_charges'];
    freeDeliveryAmount = json['free_delivery_amount'];
    distanceBasedDeliveryCharges = json['distance_based_delivery_charges'];
    perStoreDropOffFee = json['per_store_drop_off_fee'];
    handlingCharges = json['handling_charges'];
    deliveryBoyBaseFee = json['delivery_boy_base_fee'];
    deliveryBoyPerStorePickupFee = json['delivery_boy_per_store_pickup_fee'];
    deliveryBoyDistanceBasedFee = json['delivery_boy_distance_based_fee'];
    deliveryBoyPerOrderIncentive = json['delivery_boy_per_order_incentive'];
    bufferTime = json['buffer_time'];
    if (json['boundary_json'] != null) {
      boundaryJson = <BoundaryJson>[];
      json['boundary_json'].forEach((v) {
        boundaryJson!.add(BoundaryJson.fromJson(v));
      });
    }
    rushDeliveryEnabled = json['rush_delivery_enabled'];
    status = json['status'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['slug'] = slug;
    data['center_latitude'] = centerLatitude;
    data['center_longitude'] = centerLongitude;
    data['radius_km'] = radiusKm;
    data['rush_delivery_time_per_km'] = rushDeliveryTimePerKm;
    data['rush_delivery_charges'] = rushDeliveryCharges;
    data['delivery_time_per_km'] = deliveryTimePerKm;
    data['regular_delivery_charges'] = regularDeliveryCharges;
    data['free_delivery_amount'] = freeDeliveryAmount;
    data['distance_based_delivery_charges'] = distanceBasedDeliveryCharges;
    data['per_store_drop_off_fee'] = perStoreDropOffFee;
    data['handling_charges'] = handlingCharges;
    data['delivery_boy_base_fee'] = deliveryBoyBaseFee;
    data['delivery_boy_per_store_pickup_fee'] =
        deliveryBoyPerStorePickupFee;
    data['delivery_boy_distance_based_fee'] = deliveryBoyDistanceBasedFee;
    data['delivery_boy_per_order_incentive'] =
        deliveryBoyPerOrderIncentive;
    data['buffer_time'] = bufferTime;
    if (boundaryJson != null) {
      data['boundary_json'] =
          boundaryJson!.map((v) => v.toJson()).toList();
    }
    data['rush_delivery_enabled'] = rushDeliveryEnabled;
    data['status'] = status;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    return data;
  }
}

class BoundaryJson {
  double? lat;
  double? lng;

  BoundaryJson({this.lat, this.lng});

  BoundaryJson.fromJson(Map<String, dynamic> json) {
    lat = json['lat'];
    lng = json['lng'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['lat'] = lat;
    data['lng'] = lng;
    return data;
  }
}
